### ISSUE TITLE
Missing spaces around "path"

### ISSUE THREAD

**Issue by Seesicht-IT** [nalabdou/Symfony-code-snippets#1]
When using the shortcode for twig "path", the spaces after and before the curly braces are missing:
![grafik](https://user-images.githubusercontent.com/62788431/77817973-2173cd80-70cf-11ea-8a20-6f4963e3b2b6.png)
In comparison, when using the shortcode for twig "parent", then the spaces are included:
![grafik](https://user-images.githubusercontent.com/62788431/77817999-49633100-70cf-11ea-93ad-a552d2180811.png)
It also seems that the highlighting is not working for path yet, even if I include the spaces:
![grafik](https://user-images.githubusercontent.com/62788431/77818035-9810cb00-70cf-11ea-84d0-503a440b0b8a.png)
Just minor things.

**Comment by nalabdou** [comment]
fixed check the version 0.1.2

**Comment by nalabdou** [comment]
For better syntax highlighting I recommend using my theme 
https://marketplace.visualstudio.com/items?itemName=nadim-vscode.infinity-dark-theme

It is very good for symfony , twig developer :elephant:
