### ISSUE TITLE
Attribute SF6

### ISSUE THREAD

**Issue by hayusama** [nalabdou/symfony-code-snippets#13]
Hello,
I'm using the native attributes on sf6 but your plugin only adds annotations.
Is there a way to transform this?

**Comment by hayusama** [comment]
`<?php

declare(strict_types=1);

use Rector\Doctrine\Set\DoctrineSetList;
use Rector\Symfony\Set\SymfonySetList;
use Rector\Symfony\Set\SensiolabsSetList;
use Rector\Nette\Set\NetteSetList;
use Rector\Config\RectorConfig;

return function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES,
        SymfonySetList::ANNOTATIONS_TO_ATTRIBUTES,
        NetteSetList::ANNOTATIONS_TO_ATTRIBUTES,
        SensiolabsSetList::FRAMEWORK_EXTRA_61,

    ]);
    $rectorConfig->paths([__DIR__ . '/src']);

    $rectorConfig->disableParallel();
};`

To overcome this problem I use rector but would you be able to add a shortcut that allows to launch rector at worst?

**Comment by nalabdou** [comment]
Hello @hayusama,

Will see about that very soon i hope 🙏

**Comment by nalabdou** [comment]
Hello @hayusama it's little bit late, but now this extension can produce SF6 attributes
I'll close this issues feel free to reopen it if needed :)
