### ISSUE TITLE
prefix "sy" is not simple enough than just typing "sf". Can you change prefix "sy" to "sf"?

### ISSUE THREAD

**Issue by vikbert** [nalabdou/Symfony-code-snippets#2]
Can we change the prefix of snippets to "sf"? for example: sfRemove, sfUrl

**Comment by nalabdou** [comment]
next update sure.

**Comment by nalabdou** [comment]
see the update [change the prefix from sy to sf](https://github.com/nalabdou/Symfony-code-snippets/commit/cf8c3e0d596f16a7a2af2af6b53cb64ee509d472) UPDATE 0.2.4

**Comment by vikbert** [comment]
hey, nice, great job. I enjoy your work very much.

Am Mo., 21. Sept. 2020 um 18:17 Uhr schrieb Nadim alabdou <
notifications@github.com>:
