### ISSUE TITLE
[Feature Request] Code formatting for Twig files

### ISSUE THREAD

**Issue by kanlukasz** [nalabdou/Symfony-code-snippets#7]
_( I'm not sure if this is in scope of this extension, but I will try. )_

The code formatting feature for `.twig` files would be something brilliant for this plugin.
Could you consider adding this feature?

The default HTML formatter built into VSCode does not understand twig indents etc.

**Comment by nalabdou** [comment]
i will see what i can do and i'll find some time to do that soon, thanks.

**Comment by nalabdou** [comment]
Hello @kanlukasz  you can use this Formatter [Unibeautify - Universal Formatter](https://marketplace.visualstudio.com/items?itemName=Glavin001.unibeautify-vscode) for twig files && [Unibeautify - Universal Formatter](https://marketplace.visualstudio.com/items?itemName=Glavin001.unibeautify-vscode) **extension will be added to our next update**

**Comment by Rockinn** [comment]
?? ^^^

**Comment by Rockinn** [comment]
what the fuck

**Comment by nalabdou** [comment]
Hello @Rockinn , i can understand that you are looking to make your development journey much easier using this extension, but it's very important that you understand this extension is open source and i have a job to do everyday so I'm not all the time trying to make this extension suits your needs, the extension it's very helpful for many developers as it's today, if you need anything that isn't supported by default in this extension you can search any other extension i have no obligation to update or change this extension according to your needs. 
And for your question 

> what the fuck ?

This is the open source my friend, so feel free to make a pull request and i will be more than happy to accept it 😉
